parameters:

services:
    webdevvie_pheanstalktaskqueue.service:
        class: Webdevvie\PheanstalkTaskQueueBundle\Service\TaskQueueService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@webdevvie_pheanstalk_connection'
            - '@jms_serializer'
            - '%webdevvie_taskqueue.params%'

    webdevvie_pheanstalk_connection:
        class: Webdevvie\PheanstalkTaskQueueBundle\Service\PheanstalkConnection
        arguments:
            - '@webdevvie_pheanstalk_factory'
            - '%webdevvie_taskqueue.primary_server%'
            - '%webdevvie_taskqueue.default_tube%'

    webdevvie_pheanstalk_factory:
        class: Webdevvie\PheanstalkTaskQueueBundle\Service\PheanstalkFactory

    webdevvie_pheanstalk_taskqueue.task_command_generator:
        class: Webdevvie\PheanstalkTaskQueueBundle\Service\TaskCommandGenerator